# Generated by Django 5.0.4 on 2025-12-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanreport',
            name='found_directories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanreport',
            name='headers_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanreport',
            name='open_ports',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
